stages:
- name: compile
  steps:
  - runScriptConfig:
      image: maven:3.6.0
      shellScript: mvn clean package
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: demo:v3
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
