stages:
- name: compile
  steps:
  - runScriptConfig:
      image: maven:3.6.0
      shellScript: mvn clean package
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: sjhnnn/eureka:v3
      pushRemote: true
      registry: registry.cn-beijing.aliyuncs.com/shijinhao/dev
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
branch:
  include:
  - master
