stages:
- name: compile
  steps:
  - runScriptConfig:
      image: maven:3.6.0
      shellScript: mvn package
- name: publish	
  steps:	
  - publishImageConfig:	
      dockerfilePath: ./Dockerfile	
      buildContext: .	
      tag: sjhnnn/demo:${CICD_EXECUTION_SEQUENCE}	
      pushRemote: true	
      registry: registry-vpc.cn-beijing.aliyuncs.com	
- name: deploy	
  steps:	
  - applyYamlConfig:	
      path: ./deployment.yaml
timeout: 60
