stages:
- name: compile
  steps:
  - runScriptConfig:
      image: maven:3.6.0
      shellScript: mvn package
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: sjhnnn/demo:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: registry-vpc.cn-beijing.aliyuncs.com
- name: deploy
  steps:
  - runScriptConfig:
      image: gcc:latest
      shellScript: |-
        curl -k -u token-zcgsp:****************************************** \
        -X PUT \
        -H 'Accept: application/json' \
        -H 'Content-Type: application/json' \
        -d '{"containers":[{"image":"registry-vpc.cn-beijing.aliyuncs.com/sjhnnn/demo:'${CICD_EXECUTION_SEQUENCE}'","name":"snc-backed"}]}'
timeout: 60
